#
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either version
# 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If
# not, see <https://www.gnu.org/licenses/>.
#

name: Publish release

on:
  release:
    types:
      - published

env:
  DISABLE_CRATES_IO: true

jobs:
  build:
    name: Build
    permissions:
      id-token: write
      contents: read
      attestations: write
    uses: ./.github/workflows/build.yml

  publish-binaries:
    name: Upload CLI binaries to GitHub release
    permissions:
      contents: write
    if: ${{ github.event_name == 'release' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Download binary artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: List downloaded files
        run: ls -lAhR dist

      - name: Publish binaries
        run: gh release upload ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ github.token }}

  publish-to-crates-io:
    name: Publish release to crates.io
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: |
          cargo publish -p c2e
          cargo publish -p c2e-cli
          cargo publish -p c2e-wasm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
